### ISSUE TITLE
add equality test

### ISSUE THREAD

**Issue by coke** [erikwiffin/0.30000000000000004#101]
I would recommend adding another test that shows whether

0.1+0.2==0.3

in the various languages. One or two will get it right, but most do not, even the ones that print 0.3 when you do the addition.

**Comment by erikwiffin** [comment]
That's a good idea, but I don't particularly relish the idea of going through all these languages to add an equality test. If there are any particularly interesting examples, feel free to add them as a comment for individual languages.
