### ISSUE TITLE
Proposal: move this to gh-pages

### ISSUE THREAD

**Issue by sudodoki** [erikwiffin/0.30000000000000004#105]
You could leverage gh-pages build to host this site and it would work with custom domain as well.
Or you could just push to gh-pages branch an have `http://erikwiffin.github.io/0.30000000000000004` server as backup mirror. 
If you consider switching to gh-pages with domain name, you can find [instruction](https://help.github.com/articles/using-a-custom-domain-with-github-pages/)

**Comment by sudodoki** [comment]
Suggesting this because right now http://0.30000000000000004.com/ seems to be down

**Comment by mufid** [comment]
Should we close this issue since the site is now back alive again?

**Comment by waldyrious** [comment]
@mufid I still think the move would be beneficial, not only for increased reliability, but also for providing a more transparent deploy workflow (changes from merged PRs automatically become live on the website).

**Comment by erikwiffin** [comment]
Done
