### ISSUE TITLE
Allowed to Mirror?

### ISSUE THREAD

**Issue by mufid** [erikwiffin/0.30000000000000004#106]
Hey Erik Wiffin. Thanks for your initiative to build this site. Very helpful to introduce people about floating point. 

Yet, the main site: http://0.30000000000000004.com/ seems down right now so i can't refer people to this site. Currently, there is no way to access this website other than from GH repo and archive.is. Could i mirror this? I don't see LICENSE file so i ask about this. 

Also related to #105

**Comment by eneko** [comment]
Here is an archived version: http://web.archive.org/web/20161009090916/http://0.30000000000000004.com/

**Comment by mufid** [comment]
Yeah, there is one in archive.is, too. But it is kinda annoying to give people with archive domain and long URL.

**Comment by eneko** [comment]
Agreed, just pointed it out for reference. I think a mirror is out of question. Maybe the domain expired, or, guessing by the number of pull requests, the project got abandoned.

**Comment by mufid** [comment]
Hey, the site is now active again. Thanks!
