### ISSUE TITLE
Rust example no longer valid

### ISSUE THREAD

**Issue by est31** [erikwiffin/0.30000000000000004#115]
Seems the example is from before the stabilisation of Rust.

It should rather be something like [this](http://play.integer32.com/?gist=caf7ffb9548c34bbffca08bd715543ef&version=undefined).

**Comment by erikwiffin** [comment]
I've updated a bunch of languages, is Rust still out of date? If so, I'll happily merge a PR that fixes it.

**Comment by est31** [comment]
@erikwiffin its still out of date. See #117 for a PR that fixes it.
