### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by RAnders00** [erikwiffin/0.30000000000000004#122]
This is the certificate that is presented to me when I visit https://0.30000000000000004.com/:  
![image](https://cloud.githubusercontent.com/assets/1629196/26006811/26873f64-373e-11e7-99f3-5745a9551ab4.png)

The public key I was presented is issued to github.com etc..., not the domain.

**Comment by erikwiffin** [comment]
Unfortunately, there's not much I can do about that. Github pages don't support HTTPS for custom domains. Once this issue https://github.com/isaacs/github/issues/156 is resolved, I'll make sure to do whatever is required on my end to make it happen.
