### ISSUE TITLE
Common Lisp does have this issue as well, when explicitly using double floats

### ISSUE THREAD

**Issue by djeis97** [erikwiffin/0.30000000000000004#143]
Tested on both SBCL and ECL, `(+ 0.1d0 0.2d0)` does actually produce `0.30000000000000004d0`.

**Comment by erikwiffin** [comment]
Thanks @djeis97. I've added an example, but I'm not familiar with Common Lisp. Can you check my syntax for me? https://github.com/erikwiffin/0.30000000000000004/pull/148

**Comment by djeis97** [comment]
Syntax look right. I would note two things though:
- The `*` at the start of the other three examples is the traditional prompt at a lisp console/REPL, so I’d suggest adding it to the new example or dropping it from the other three for consistency.
- I’d also suggest adding a note along the lines of “CL’s spec doesn’t actually even require radix 2 floats (let alone specifically 32-bit singles and 64-bit doubles), but the high-performance implementations all seem to use IEEE floats with the usual sizes. This was tested on SBCL and ECL in particular.”

**Comment by erikwiffin** [comment]
Thanks for those notes. Examples updated and merged.
