### ISSUE TITLE
Font size is too small

### ISSUE THREAD

**Issue by chris-morgan** [erikwiffin/0.30000000000000004#168]
12px is much too small. I recommend leaving it at the default (normally 16px), and defining most other things in terms of ems or rems instead of pixels, and using `max-width: 100%` so that the greater width isn’t causing overflow trouble unnecessarily. (Mostly you could instead change `width`s to `max-width`s, but some bits may need to be told to be as wide as possible within that.)

**Comment by erikwiffin** [comment]
Thanks for the feedback. The entire page is in need of a redesign, I'll definitely keep font size in mind at that time.
