### ISSUE TITLE
Raku output is truncated

### ISSUE THREAD

**Issue by 0racle** [erikwiffin/0.30000000000000004#172]
Although the markdown source for Raku shows the correct output to `raku -e 'say (0.1 + 0.2).fmt("%.17f")'` is `0.30000000000000000`, on the published website just shows the output as `0.3`.

**Comment by 0racle** [comment]
Seems I can just stringify the output to prevent it being rounded down. PR #173 has been raised.

**Comment by erikwiffin** [comment]
#173 is merged.
