### ISSUE TITLE
The Hyperlink of Mathematica is Unavaliable now

### ISSUE THREAD

**Issue by linuxbckp** [erikwiffin/0.30000000000000004#177]
# https://reference.wolfram.com/language/tutorial/NumericalPrecision.html
The website shows "可以使用以上搜索栏查询整个网站，或者尝试以下链接。" in Chinese, which mean "You may use search bar or try the following link(s)."
Maybe you should replace or delete this hyperlink.

**Comment by erikwiffin** [comment]
Thanks for letting me know. This should be fixed by https://github.com/erikwiffin/0.30000000000000004/commit/90b7d57f68991bc4e2aeda57ffc069ccd809de81
