### ISSUE TITLE
Add GNU Octave Code and Results

### ISSUE THREAD

**Issue by linuxbckp** [erikwiffin/0.30000000000000004#178]
The results are partially different with which in Matlab.
# File:
---
layout: post
title: 'GNU Octave'
code:
  - 0.1 + 0.2
  - single(0.1)+single(0.2)
  - double(0.1)+double(0.2)
  - 0.1+single(0.2)
  - 0.1+double(0.2)
  - "sprintf('%.17f',0.1+0.2)"
result:
  - 0.30000
  - 0.30000
  - 0.30000
  - 0.30000
  - 0.30000
  - 0.30000000000000004
---
# Additionally, I met an error-403 while "git push". Could you give me the push permission?

**Comment by erikwiffin** [comment]
I don't want to give out push permission, but if you clone the repo you can push to that, and make a PR from there - I'll be happy to merge it.

**Comment by linuxbckp** [comment]
OK I made a PR.

**Comment by erikwiffin** [comment]
Merged, thanks!
