### ISSUE TITLE
The APL result is wrong

### ISSUE THREAD

**Issue by linuxbckp** [erikwiffin/0.30000000000000004#184]
I will open a PR later.
![wrong_apl_result](https://user-images.githubusercontent.com/60608216/83145129-ed487780-a126-11ea-8bd6-6c751f20a803.png)
![correct_a+](https://user-images.githubusercontent.com/60608216/83145207-09e4af80-a127-11ea-87d1-ce9835e521db.png)

**Comment by abrudz** [comment]
Addressed in [my PR](https://github.com/erikwiffin/0.30000000000000004/pull/188) too.

**Comment by erikwiffin** [comment]
Merged #188
