### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by LuisEnMarroquin** [erikwiffin/0.30000000000000004#192]
Hi there, GitHub has an option to redirect the traffic from HTTP to HTTPS, it's in the project settings under the GitHub Pages section

![image](https://user-images.githubusercontent.com/35376824/93619713-8b926e80-f99e-11ea-91ae-b1e7e5c6af09.png)

![image](https://user-images.githubusercontent.com/35376824/93619468-30607c00-f99e-11ea-9020-f4b49e57772e.png)

**Comment by erikwiffin** [comment]
Thanks for the catch. I've enabled it.
