### ISSUE TITLE
python has a Decimal module

### ISSUE THREAD

**Issue by ZeeD** [erikwiffin/0.30000000000000004#24]
https://docs.python.org/library/decimal.html

**Comment by tgs** [comment]
Example:

```python
>>> from decimal import Decimal
>>> Decimal('0.1') + Decimal('0.2')
Decimal('0.3')
```

**Comment by erikwiffin** [comment]
Someone provided a pull request for the Decimal module. https://github.com/erikwiffin/0.30000000000000004/pull/39 Does that cover it?

**Comment by tgs** [comment]
Sure, that's a reasonable way to show it.
