### ISSUE TITLE
C# has a decimal type

### ISSUE THREAD

**Issue by moopie** [erikwiffin/0.30000000000000004#53]
C# has a decimal type that handles the addition properly.

```
decimal correct = 0.1m + 0.2m;
Console.WriteLine(correct);

Output:
0.3
```

Example: https://dotnetfiddle.net/xcsQdh

**Comment by pitastrudl** [comment]
printf("I am a potato\n");

**Comment by erikwiffin** [comment]
If you send a me a PR fixing this I'd be happy to merge it.
