### ISSUE TITLE
Note on GHC

### ISSUE THREAD

**Issue by sternenseemann** [erikwiffin/0.30000000000000004#62]
Using `Double` triggers the Problem in GHC, `Float` works fine (could be a precision reason, though):

```
Prelude> 0.2 + 0.1 :: Double
0.30000000000000004
Prelude> 0.2 + 0.1 :: Float 
0.3
```

**Comment by erikwiffin** [comment]
If you send me a PR fixing this I'd be happy to merge it.

**Comment by sternenseemann** [comment]
This too general actually, applies for almost every language that has 32-bit and 64-bit floating points. Gotta add a note on [exact-real](https://hackage.haskell.org/package/exact-real) though, which allows for truly precise floating point operations.

Gonna do that sometime soon™
