### ISSUE TITLE
[C++] setprecision() uses the std namespace

### ISSUE THREAD

**Issue by Bruflot** [erikwiffin/0.30000000000000004#68]
The C++ example is as follows:

``` c++
std::cout << setprecision(17) << 0.1 + 0.2 << std.endl;
```

The function `setprecision()` uses the std namespace, and should therefore be written as such. Same goes for `endl`. Furthermore, the C example also works in C++; perhaps these should be merged?

**Comment by erikwiffin** [comment]
If you send me a PR on the subject I'd be happy to merge it.
