### ISSUE TITLE
Link to published website

### ISSUE THREAD

**Issue by omnidan** [erikwiffin/0.30000000000000004#7]
Is this repo published somewhere? It would be a good idea to include a link to the published website in this repos README.md

**Comment by dbkaplun** [comment]
+1

An easy way to publish this is to simply push a `gh-pages` branch. It will then be available at https://erikwiffin.github.io/0.30000000000000004

**Comment by erikwiffin** [comment]
I've updated the readme, the repo is currently published at http://0.30000000000000004.com/
